services:
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service
      - user-service
      - frontend

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./auth-service:/app
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=d4f5e8b7c3d4e2f5a8c3b7d4e8f5c2b7e3f5d4c2a8b7e4f5
      - DEBUG=True
    command: >
      flask run --host=0.0.0.0 --port=5001

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./user-service:/app
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=d4f5e8b7c3d4e2f5a8c3b7d4e8f5c2b7e3f5d4c2a8b7e4f5
      - DEBUG=True
    command: >
      flask run --host=0.0.0.0 --port=5002

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    environment:
      - NODE_ENV=development